
//harvester creeps
const HARVESTER_SCHEMA = [
    [WORK, CARRY, MOVE],
    [WORK, WORK, CARRY, MOVE, MOVE, MOVE]
]

//upgrader creeps
const UPGRADER_SCHEMA = [
    [WORK, CARRY, MOVE],
    [WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE]
]

const BUILDER_SCHEMA = [
    [WORK, CARRY, MOVE],
    [WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE]
]

const FLOATER_SCHEMA = [
    [WORK, CARRY, MOVE],
    [WORK, WORK, CARRY, CARRY, MOVE, MOVE]
]

export {
    HARVESTER_SCHEMA,
    UPGRADER_SCHEMA,
    BUILDER_SCHEMA,
    FLOATER_SCHEMA
}
