
//harvester creeps
const HARVESTER_SCHEMA = [
    [WORK, WORK, MOVE],
    [WORK, WORK, MOVE]
]

//upgrader creeps
const UPGRADER_SCHEMA = [
    [WORK, CARRY, MOVE],
    [WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE]
]

const BUILDER_SCHEMA = [
    [WORK, CARRY, MOVE],
    [WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE]
]

const FLOATER_SCHEMA = [
    [WORK, CARRY, MOVE],
    [WORK, WORK, CARRY, CARRY, MOVE, MOVE]
]

const HAULER_SCHEMA = [
    [CARRY, CARRY, MOVE, MOVE],
    [CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE]
]

const RUNNER_SCHEMA = [
    [CARRY, MOVE]
]

const HOME_ROOM = 'W12N56'
const HOME_SPAWN = 'Spawn1'

const FILL_PRIORITY = [STRUCTURE_SPAWN, STRUCTURE_TOWER, STRUCTURE_EXTENSION, STRUCTURE_CONTAINER, STRUCTURE_STORAGE]
const RETRIEVE_PRIORITY = [STRUCTURE_STORAGE, STRUCTURE_CONTAINER]

export {
    HARVESTER_SCHEMA,
    UPGRADER_SCHEMA,
    BUILDER_SCHEMA,
    FLOATER_SCHEMA,
    HAULER_SCHEMA,
    RUNNER_SCHEMA,
    HOME_ROOM,
    HOME_SPAWN,
    FILL_PRIORITY,
    RETRIEVE_PRIORITY
}

